#:kivy 1.8.0
<DrawingGame>:
    BoxLayout:
        size_hint: .1, .1
        orientation: 'horizontal'
        padding: 10
        spacing: 20
        
        TextInput:
            id: level_number
            hint_text: 'Enter level suffix'
            multiline: False
            on_text_validate: root.text_entered()

        Button:
            text: 'save'
            on_press: root.save_level()

        

